# -*- coding: utf-8 -*-
"""App.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1IRkvuhtc2cDEvuBNR0QQgfCdPkIxaWm4
"""

import streamlit as st
import numpy as np
import onnxruntime as ort

@st.cache_resource
def load_model():
    return ort.InferenceSession("diabetes_model.onnx")

session = load_model()

st.title("Decision Tree ONNX Model")
st.write("Enter the input values separated by commas")

input_str = st.text_input("Number of Pregnancies ,Glucose Level ,Blood Pressure ,SkinThickness ,Insulin ,BMI ,DiabetesPedigreeFunction ,Age ")

if st.button("Predict"):
    try:
        input_array = np.array([list(map(float, input_str.strip().split(',')))], dtype=np.float32)

        input_name = session.get_inputs()[0].name
        ort_inputs = {input_name: input_array}

        pred = session.run(None, ort_inputs)
        st.success(f"Prediction result: {pred[0][0]}")
    except Exception as e:
        st.error(f"Error occurred: {e}")
